#
# Copyright (C) 2020 AVNET Integrated, <avnet-integrated.eu>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation version 2.
#
# This program is distributed "as is" WITHOUT ANY WARRANTY of any
# kind, whether express or implied; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

# MES revision B0 is software compatible to A0
# C0 is same as B0 but is actually using the industrial/automotive CPU.
# Automotive detection will be handled by the SCFW
dtb-$(CONFIG_ARCH_FSL_IMX8QM) += \
	msc-sm2s-imx8-C0-module-qcm-14N06A0I.dtb \
	msc-sm2s-imx8-C0-module-qcm-24N06A0I.dtb \
	msc-sm2s-imx8-C0-module-qcm-24N06E1I.dtb \
	msc-sm2s-imx8-C0-module-qcm-24N06E0I.dtb \
	msc-sm2s-imx8-C0-module-qcm-24N0CE1I.dtb \
	msc-sm2s-imx8-C0-module-qcm-24N0CF0I.dtb \
	\
	msc-sm2s-imx8-C0-module-qcm-14N06A0I-pciex2.dtb \
	msc-sm2s-imx8-C0-module-qcm-24N06A0I-pciex2.dtb \
	msc-sm2s-imx8-C0-module-qcm-24N06E1I-pciex2.dtb \
	msc-sm2s-imx8-C0-module-qcm-24N06E0I-pciex2.dtb \
	msc-sm2s-imx8-C0-module-qcm-24N0CE1I-pciex2.dtb \
	msc-sm2s-imx8-C0-module-qcm-24N0CF0I-pciex2.dtb \
	\
	msc-sm2s-imx8-C0-module-qcp-14N06A0I.dtb \
	msc-sm2s-imx8-C0-module-qcp-24N06A0I.dtb \
	msc-sm2s-imx8-C0-module-qcp-24N06E1I.dtb \
	msc-sm2s-imx8-C0-module-qcp-24N0CE1I.dtb \
	msc-sm2s-imx8-C0-module-qcp-24N0CF0I.dtb \
	\
	msc-sm2s-imx8-C0-baseboard-none.dtb \
	msc-sm2s-imx8-C0-baseboard-sm2-mb-ep1-A0.dtb \
	msc-sm2s-imx8-C0-baseboard-sm2-mb-ep1-dual-csi2-A0.dtb \
	\
	msc-sm2s-imx8-C0-baseboard-sm2s-mb-ep5-002-A0.dtb \
	msc-sm2s-imx8-C0-baseboard-sm2s-mb-ep5-004-A0.dtb \
	msc-sm2s-imx8-C0-baseboard-sm2s-mb-ep5-102-A0.dtb \
	\
	msc-sm2s-imx8-C0-baseboard-afts2019-10.dtb \
	\
	msc-sm2s-imx8-C0-display-AMA-070A04-DU2511-G010.dtb \
	msc-sm2s-imx8-C0-display-AMA-121A01-DU2511-G010.dtb \
	msc-sm2s-imx8-C0-display-AMA-121A01-DU2511-G010-dual.dtb \
	msc-sm2s-imx8-C0-display-AUO-B170UW02.dtb \
	msc-sm2s-imx8-C0-display-RAYDIUM-RM67191.dtb \
	msc-sm2s-imx8-C0-display-xinli-x078dtlt-119.dtb \
	msc-sm2s-imx8-C0-display-hdmi.dtb \
	msc-sm2s-imx8-C0-display-dp.dtb \
	\
	msc-sm2s-imx8-B0-module-qcm-14N06A0I.dtb \
	msc-sm2s-imx8-B0-module-qcm-24N06A0I.dtb \
	msc-sm2s-imx8-B0-module-qcm-24N06E1I.dtb \
	msc-sm2s-imx8-B0-module-qcm-24N06E0I.dtb \
	msc-sm2s-imx8-B0-module-qcm-24N0CE1I.dtb \
	msc-sm2s-imx8-B0-module-qcm-24N0CF0I.dtb \
	\
	msc-sm2s-imx8-B0-module-qcm-14N06A0I-pciex2.dtb \
	msc-sm2s-imx8-B0-module-qcm-24N06A0I-pciex2.dtb \
	msc-sm2s-imx8-B0-module-qcm-24N06E1I-pciex2.dtb \
	msc-sm2s-imx8-B0-module-qcm-24N06E0I-pciex2.dtb \
	msc-sm2s-imx8-B0-module-qcm-24N0CE1I-pciex2.dtb \
	msc-sm2s-imx8-B0-module-qcm-24N0CF0I-pciex2.dtb \
	\
	msc-sm2s-imx8-B0-module-qcp-14N06A0I.dtb \
	msc-sm2s-imx8-B0-module-qcp-24N06A0I.dtb \
	msc-sm2s-imx8-B0-module-qcp-24N06E1I.dtb \
	msc-sm2s-imx8-B0-module-qcp-24N0CE1I.dtb \
	msc-sm2s-imx8-B0-module-qcp-24N0CF0I.dtb \
	\
	msc-sm2s-imx8-B0-baseboard-none.dtb \
	msc-sm2s-imx8-B0-baseboard-sm2-mb-ep1-A0.dtb \
	msc-sm2s-imx8-B0-baseboard-sm2-mb-ep1-dual-csi2-A0.dtb \
	\
	msc-sm2s-imx8-B0-baseboard-sm2s-mb-ep5-002-A0.dtb \
	msc-sm2s-imx8-B0-baseboard-sm2s-mb-ep5-004-A0.dtb \
	msc-sm2s-imx8-B0-baseboard-sm2s-mb-ep5-102-A0.dtb \
	\
	msc-sm2s-imx8-B0-baseboard-afts2019-10.dtb \
	\
	msc-sm2s-imx8-B0-display-AMA-070A04-DU2511-G010.dtb \
	msc-sm2s-imx8-B0-display-AMA-121A01-DU2511-G010.dtb \
	msc-sm2s-imx8-B0-display-AMA-121A01-DU2511-G010-dual.dtb \
	msc-sm2s-imx8-B0-display-AUO-B170UW02.dtb \
	msc-sm2s-imx8-B0-display-RAYDIUM-RM67191.dtb \
	msc-sm2s-imx8-B0-display-xinli-x078dtlt-119.dtb \
	msc-sm2s-imx8-B0-display-hdmi.dtb \
	msc-sm2s-imx8-B0-display-dp.dtb \
	\
	msc-sm2s-imx8-A0-module-qcm-14N06A0I.dtb \
	msc-sm2s-imx8-A0-module-qcm-24N06A0I.dtb \
	msc-sm2s-imx8-A0-module-qcm-24N06E1I.dtb \
	msc-sm2s-imx8-A0-module-qcm-24N06E0I.dtb \
	msc-sm2s-imx8-A0-module-qcm-24N0CE1I.dtb \
	msc-sm2s-imx8-A0-module-qcm-24N0CF0I.dtb \
	\
	msc-sm2s-imx8-A0-module-qcm-14N06A0I-pciex2.dtb \
	msc-sm2s-imx8-A0-module-qcm-24N06A0I-pciex2.dtb \
	msc-sm2s-imx8-A0-module-qcm-24N06E1I-pciex2.dtb \
	msc-sm2s-imx8-A0-module-qcm-24N06E0I-pciex2.dtb \
	msc-sm2s-imx8-A0-module-qcm-24N0CE1I-pciex2.dtb \
	msc-sm2s-imx8-A0-module-qcm-24N0CF0I-pciex2.dtb \
	\
	msc-sm2s-imx8-A0-module-qcp-14N06A0I.dtb \
	msc-sm2s-imx8-A0-module-qcp-24N06A0I.dtb \
	msc-sm2s-imx8-A0-module-qcp-24N06E1I.dtb \
	msc-sm2s-imx8-A0-module-qcp-24N06E0I.dtb \
	msc-sm2s-imx8-A0-module-qcp-24N0CE1I.dtb \
	msc-sm2s-imx8-A0-module-qcp-24N0CF0I.dtb \
	\
	msc-sm2s-imx8-A0-baseboard-none.dtb \
	msc-sm2s-imx8-A0-baseboard-sm2-mb-ep1-A0.dtb \
	msc-sm2s-imx8-A0-baseboard-sm2-mb-ep1-dual-csi2-A0.dtb \
	\
	msc-sm2s-imx8-A0-baseboard-sm2s-mb-ep5-002-A0.dtb \
	msc-sm2s-imx8-A0-baseboard-sm2s-mb-ep5-004-A0.dtb \
	msc-sm2s-imx8-A0-baseboard-sm2s-mb-ep5-102-A0.dtb \
	\
	msc-sm2s-imx8-A0-baseboard-afts2019-10.dtb \
	\
	msc-sm2s-imx8-A0-display-AMA-070A04-DU2511-G010.dtb \
	msc-sm2s-imx8-A0-display-AMA-121A01-DU2511-G010.dtb \
	msc-sm2s-imx8-A0-display-AMA-121A01-DU2511-G010-dual.dtb \
	msc-sm2s-imx8-A0-display-AUO-B170UW02.dtb \
	msc-sm2s-imx8-A0-display-RAYDIUM-RM67191.dtb \
	msc-sm2s-imx8-A0-display-xinli-x078dtlt-119.dtb \
	msc-sm2s-imx8-A0-display-hdmi.dtb \
	msc-sm2s-imx8-A0-display-dp.dtb \
	\
	msc-sm2s-imx8-20-module-qcm-14N06A0I.dtb \
	msc-sm2s-imx8-20-module-qcm-24N06A0I.dtb \
	msc-sm2s-imx8-20-module-qcm-24N06E1I.dtb \
	msc-sm2s-imx8-20-module-qcm-24N06E0I.dtb \
	msc-sm2s-imx8-20-module-qcm-24N0CE1I.dtb \
	msc-sm2s-imx8-20-module-qcm-24N0CF0I.dtb \
	\
	msc-sm2s-imx8-20-module-qcm-14N06A0I-pciex2.dtb \
	msc-sm2s-imx8-20-module-qcm-24N06A0I-pciex2.dtb \
	msc-sm2s-imx8-20-module-qcm-24N06E1I-pciex2.dtb \
	msc-sm2s-imx8-20-module-qcm-24N06E0I-pciex2.dtb \
	msc-sm2s-imx8-20-module-qcm-24N0CE1I-pciex2.dtb \
	msc-sm2s-imx8-20-module-qcm-24N0CF0I-pciex2.dtb \
	\
	msc-sm2s-imx8-20-module-qcp-14N06A0I.dtb \
	msc-sm2s-imx8-20-module-qcp-24N06A0I.dtb \
	msc-sm2s-imx8-20-module-qcp-24N06E1I.dtb \
	msc-sm2s-imx8-20-module-qcp-24N0CE1I.dtb \
	msc-sm2s-imx8-20-module-qcp-24N0CF0I.dtb \
	\
	msc-sm2s-imx8-20-baseboard-none.dtb \
	msc-sm2s-imx8-20-baseboard-sm2-mb-ep1-A0.dtb \
	msc-sm2s-imx8-20-baseboard-sm2-mb-ep1-dual-csi2-A0.dtb \
	\
	msc-sm2s-imx8-20-baseboard-sm2s-mb-ep5-002-A0.dtb \
	msc-sm2s-imx8-20-baseboard-sm2s-mb-ep5-004-A0.dtb \
	msc-sm2s-imx8-20-baseboard-sm2s-mb-ep5-102-A0.dtb \
	\
	msc-sm2s-imx8-20-baseboard-afts2019-10.dtb \
	\
	msc-sm2s-imx8-20-display-AMA-121A01-DU2511-G010.dtb \
	msc-sm2s-imx8-20-display-AMA-121A01-DU2511-G010-dual.dtb \
	msc-sm2s-imx8-20-display-AUO-B170UW02.dtb \
	msc-sm2s-imx8-20-display-hdmi.dtb \
	msc-sm2s-imx8-20-display-dp.dtb \

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
