#
# Copyright (C) 2022 Avnet Embedded GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the termsof the GNU General Public License as
# published by the Free Software Foundation version 2.
#
# This program is distributed "as is" WITHOUT ANY WARRANTY of any
# kind, whether express or implied; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

dtb-$(CONFIG_IMX8MN) += \
	msc-sm2s-imx8mlc-nano-02N0230E-module.dtb \
	msc-sm2s-imx8mlc-nano-02N0830E-module.dtb \
	msc-sm2s-imx8mlc-nano-03N0220I-module.dtb \
	msc-sm2s-imx8mlc-nano-03N0820I-module.dtb \
	msc-sm2s-imx8mlc-nano-13N0220I-module.dtb \
	msc-sm2s-imx8mlc-nano-14N0201C-module.dtb \
	msc-sm2s-imx8mlc-nano-92N0830E-module.dtb \
	overlay-baseboard-ep1.dtb \
	overlay-baseboard-ep5.dtb \
	overlay-baseboard-vebo.dtb \
	overlay-dsi-boe-gv101wum-ls0.dtb \
	overlay-dsi-rm67191.dtb \
	overlay-lvds-ama-070a04.dtb \
	overlay-lvds-ama-101a01.dtb \
	overlay-lvds-ama-101a07.dtb \
	overlay-lvds-ama-121a01.dtb \
	overlay-lvds-auo-p215hvn01.dtb \
	overlay-cam-ov5640.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
