# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += msc-sm2s-imx93-92N0870E-module.dtb
dtb-$(CONFIG_ARCH_MXC) += msc-sm2s-imx93-14N02C1I-module.dtb
dtb-$(CONFIG_ARCH_MXC) += overlay-baseboard-vebo.dtb
dtb-$(CONFIG_ARCH_MXC) += overlay-baseboard-ep1.dtb
dtb-$(CONFIG_ARCH_MXC) += overlay-baseboard-ep5.dtb
dtb-$(CONFIG_ARCH_MXC) += overlay-dsi-rm67191.dtb
dtb-$(CONFIG_ARCH_MXC) += overlay-dsi-boe-gv101wum-ls0.dtb
dtb-$(CONFIG_ARCH_MXC) += overlay-lvds-ama-070a04.dtb
dtb-$(CONFIG_ARCH_MXC) += overlay-lvds-ama-101a01.dtb
dtb-$(CONFIG_ARCH_MXC) += overlay-lvds-ama-101a07.dtb
dtb-$(CONFIG_ARCH_MXC) += overlay-lvds-ama-121a01.dtb
dtb-$(CONFIG_ARCH_MXC) += overlay-cam-ov5640.dtb
